#!/bin/sh

sleep 3

case "$1" in
start)
        brcm_patchram_plus1 --bd_addr_rand --enable_hci --no2bytes --use_baudrate_for_download  --tosleep  200000 --baudrate 1500000 --patchram /etc/firmware/BCM4362A2.hcd  /dev/ttymxc0  &
	sleep 2
	rfkill unblock all
	ifconfig wlan0 up
	hciconfig hci0 up
        ;;
stop)
        ;;
esac
exit 0
